version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "raw_data_events:1:1"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: feature_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fouzia
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  kafka-consumer-service:
    build:
      context: ./kafka_consumer_service
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: raw_data_events
      POSTGRES_HOST: postgres
      POSTGRES_DB: feature_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fouzia

  prediction-api-service:
    build:
      context: ./prediction-api-service
    ports:
      - "8000:8000"
    volumes:
      - ./prediction-api-service:/app:cached
    environment:
      MODEL_PATH: /app/model.pkl
      MODEL_VERSION: 1.0.0

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.0
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
